### ISSUE TITLE
Are `_proof` and `_publicInputs` actually unused?

### ISSUE THREAD

**Issue by phated** [AztecProtocol/aztec-verifier-contracts#20]
The linters in Remix IDE claim that `_proof` and `_publicInputs` variables on the `verify` function are unused. Is this just a false positive?

**Comment by TomAFrench** [comment]
This is a false positive. These two arguments are being read directly from within assembly by using the `calldataload` function.

solc is notoriously bad at not allowing us to disable warnings to the point that hardhat and foundry have patched around it: https://github.com/ethereum/solidity/issues/2675

**Comment by LHerskind** [comment]
As @TomAFrench says. We kept the names in there to make it more understandable, as just have two unnamed args can be pretty unhelpful.
